name: "Spellcheck"
on: pull_request, push
description: "Runs write-good on all md files"
runs:
  using: "composite"
  steps:
  - run: echo Testing
      shell: bash
    - run: ./entrypoint.sh
      shell: bash
